name: lumi
description: "A personal assistant for any usecase."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  dotted_border: ^3.1.0
  popover: ^0.3.1
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  pinput: ^5.0.1
  country_picker: ^2.0.27

  http: ^1.5.0
  sqflite: ^2.4.2
  dio: ^5.9.0
  floor: ^1.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

  uuid: ^4.5.1
  equatable: ^2.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo/app_logo.png
  android: true
  android_gravity: center
  fullscreen: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - .env
